# Generated by Django 3.1.4 on 2021-01-05 08:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20210105_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='min_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum price'),
        ),
    ]
